
// THE TRICK HERE IS IF ANYONE IS LEFT WITH THE NO. OF STONES, MULTIPLE OF 4; WILL BE STUCKED IN THE LOOP 
// WHERE HE WILL ALWAYS HAVE THE STONES IN THE MULTIPLES OF 4 AND FINALLY WILL BE LEFT WITH 4 STONES,
// WHERE HE HAS TO REMOVE ATLEAST 1 STONE AND HE WILL LOSE

bool canWinNim(int n)
{
    return (n % 4);
}